---
version: 1.4.0
slug: cups
name: CUPS Print Server
description: CUPS print server for network printing
url: https://github.com/tobiasfrejo/ha-cups
codenotary: tobias@frejo.dk
arch:
  - aarch64
  - amd64
hassio_api: true
host_network: true
usb: true
map:
  - data:rw
  - share:rw
init: false
ports:
  631/tcp: 631
  631/udp: 631
ports_description:
  631/tcp: CUPS web interface and printing port
  631/udp: IPP browsing / AirPrint
options:
  admin_username: "admin"
  admin_password: "admin"
  printer_driver_deb: ""
schema:
  admin_username: str
  admin_password: password
  printer_driver_deb: str
startup: services
